//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CD_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD
    {
        public int cdID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string Section { get; set; }
        public string xPos { get; set; }
        public string yPos { get; set; }
        public int Barcode { get; set; }
        public string OnLoan { get; set; }
        public string cdFileName { get; set; }
    }
}
